
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using NUnit.Framework;

namespace ApiTest
{
    class Program
    {
        static void Main(string[] args)
        {
            GoogleAccessTest test = new GoogleAccessTest();
            test.SetUp();
            test.recordingTest();
            test.TearDown();
            Console.WriteLine("Script ran successfully");
        }

    }
}

// Generated by Selenium IDE

[TestFixture]
public class GoogleAccessTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    public void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void recordingTest()
    {
        driver.Navigate().GoToUrl("https://www.google.com/search?client=firefox-b-d&q=hey");
        driver.Manage().Window.Size = new System.Drawing.Size(1550, 838);
        driver.FindElement(By.LinkText("Imagens")).Click();
        driver.FindElement(By.CssSelector(".islrc > .isv-r:nth-child(2) .rg_i")).Click();
        js.ExecuteScript("window.scrollTo(0,191.1999969482422)");
        //driver.FindElement(By.CssSelector(".EVPn8e:nth-child(2) > .isv-r:nth-child(1) .WGvvNb")).Click();
    }
}
